"""INDEX.md generation from frontmatter.

Scans all .md files in a directory, reads frontmatter, and writes INDEX.md.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from .doc import DocMeta, parse_frontmatter

INDEX_HEADER = "<!-- AUTO-GENERATED by docctl index - do not hand-edit -->\n"


@dataclass
class IndexEntry:
    title: str
    file: str       # filename only, relative to the directory
    category: str
    status: str
    created: str
    tags: list[str] = field(default_factory=list)


def _collect_entries(directory: Path) -> list[IndexEntry]:
    entries = []
    for md_path in sorted(directory.rglob("*.md")):
        if md_path.name == "INDEX.md":
            continue
        # Only files directly in the directory (not deep subdirs) for the table,
        # but we do include subdirectory files at depth 1 (briefings/, reviews/)
        rel = md_path.relative_to(directory)
        text = md_path.read_text(encoding="utf-8", errors="replace")
        meta, _ = parse_frontmatter(text)
        if meta is None:
            entries.append(IndexEntry(
                title=md_path.stem.replace("-", " ").replace("_", " ").title(),
                file=str(rel),
                category="",
                status="",
                created="",
            ))
        else:
            entries.append(IndexEntry(
                title=meta.title or md_path.stem,
                file=str(rel),
                category=meta.category,
                status=meta.status,
                created=meta.created,
                tags=meta.tags,
            ))
    return entries


def _render_table(entries: list[IndexEntry]) -> str:
    lines = []
    lines.append("| Title | File | Category | Status | Created |")
    lines.append("|-------|------|----------|--------|---------|")
    for e in entries:
        title = e.title.replace("|", "/")
        fname = e.file.replace("|", "/")
        lines.append(f"| {title} | {fname} | {e.category} | {e.status} | {e.created} |")
    return "\n".join(lines) + "\n"


def rebuild(directory: Path) -> str:
    """Build INDEX.md content for the given directory. Returns the content string."""
    entries = _collect_entries(directory)
    dir_name = directory.name
    content = f"# {dir_name}/ Index\n{INDEX_HEADER}\n"
    if entries:
        content += _render_table(entries)
    else:
        content += "_No documents found._\n"
    return content


def write_index(directory: Path) -> Path:
    """Rebuild and write INDEX.md in the directory. Returns the path written."""
    content = rebuild(directory)
    out = directory / "INDEX.md"
    out.write_text(content, encoding="utf-8")
    return out


@dataclass
class VerifyResult:
    status: str   # OK | STALE | MISSING
    file: str
    detail: str = ""


def verify(directory: Path) -> list[VerifyResult]:
    """Compare INDEX.md entries against actual files in the directory.

    Returns list of VerifyResult for each anomaly found.
    """
    index_path = directory / "INDEX.md"
    if not index_path.exists():
        return [VerifyResult(status="MISSING", file="INDEX.md",
                             detail="INDEX.md does not exist")]

    index_text = index_path.read_text(encoding="utf-8", errors="replace")

    # Extract file references from the markdown table
    import re
    # Match table data rows (not header rows): | ... | filename.md | ... |
    file_pattern = re.compile(r"\|\s*[^|]+\|\s*([^|]+\.md)\s*\|")
    indexed_files: set[str] = set()
    for m in file_pattern.finditer(index_text):
        fname = m.group(1).strip()
        indexed_files.add(fname)

    # Collect actual files
    actual_files: set[str] = set()
    for md_path in sorted(directory.rglob("*.md")):
        if md_path.name == "INDEX.md":
            continue
        rel = str(md_path.relative_to(directory))
        actual_files.add(rel)

    results = []

    # Files in index but not on disk
    for f in sorted(indexed_files - actual_files):
        results.append(VerifyResult(status="STALE", file=f,
                                    detail="in INDEX.md but not on disk"))

    # Files on disk but not in index
    for f in sorted(actual_files - indexed_files):
        results.append(VerifyResult(status="MISSING", file=f,
                                    detail="on disk but not in INDEX.md"))

    return results
