apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: halo-data
  namespace: halo-aura
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vultr-block-storage-hdd
  resources:
    requests:
      storage: 40Gi  # Vultr minimum
