"""Provisioning logic for microHAL instances."""

import os
import shutil
import stat
from datetime import datetime, timezone
from pathlib import Path

try:
    import yaml
except ImportError:
    from halos.nightctl import yaml_shim as yaml

from halos.common.log import hlog
from .config import load_fleet_config, fleet_dir, load_fleet_manifest, save_fleet_manifest
from .templates import compose_claude_md


def _make_ignore_fn(exclude_list: list[str]):
    """Build a shutil.copytree ignore function from the exclude list."""
    def _ignore(directory: str, contents: list[str]) -> set[str]:
        ignored = set()
        for item in contents:
            for pattern in exclude_list:
                pattern_clean = pattern.rstrip("/")
                # Match exact name or directory prefix
                if item == pattern_clean:
                    ignored.add(item)
                elif item.startswith(pattern_clean):
                    ignored.add(item)
                # Handle .env* glob
                elif pattern_clean.endswith("*") and item.startswith(pattern_clean[:-1]):
                    ignored.add(item)
            # Also skip __pycache__ and .git
            if item in ("__pycache__", ".git", "node_modules"):
                ignored.add(item)
        return ignored
    return _ignore


def _apply_lock(path: Path, items: list[str]) -> None:
    """Set locked items to read-only (444 for files, 555 for dirs)."""
    for item in items:
        target = path / item
        if not target.exists():
            continue
        if target.is_dir():
            for root, dirs, files in os.walk(target):
                os.chmod(root, stat.S_IRUSR | stat.S_IRGRP | stat.S_IROTH |
                         stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)  # 555
                for f in files:
                    os.chmod(os.path.join(root, f),
                             stat.S_IRUSR | stat.S_IRGRP | stat.S_IROTH)  # 444
        else:
            os.chmod(target, stat.S_IRUSR | stat.S_IRGRP | stat.S_IROTH)  # 444


def _create_open_dirs(path: Path, items: list[str]) -> None:
    """Create open directories with full rwx."""
    for item in items:
        target = path / item
        target.mkdir(parents=True, exist_ok=True)


def _generate_ecosystem_config(name: str, deploy_path: Path, token_env: str) -> str:
    """Generate pm2 ecosystem config content for an instance."""
    return f"""// pm2 ecosystem config for microhal-{name}
// Generated by halctl — do not edit manually.
module.exports = {{
  apps: [{{
    name: "microhal-{name}",
    cwd: "{deploy_path}",
    script: "npm",
    args: "start",
    env: {{
      NODE_ENV: "production",
      TELEGRAM_BOT_TOKEN_ENV: "{token_env}",
      MICROHAL_NAME: "{name}",
    }},
    watch: false,
    autorestart: true,
    max_restarts: 10,
    restart_delay: 5000,
  }}],
}};
"""


def create_instance(
    name: str,
    personality: str | None = None,
    config_path: Path | None = None,
    fleet_base: Path | None = None,
) -> dict:
    """Provision a new microHAL instance.

    Returns the instance manifest entry dict.
    """
    cfg = load_fleet_config(config_path)
    base = cfg["base"]
    profiles = cfg.get("profiles", {})

    # Resolve personality from profile or fallback to default
    profile = profiles.get(name, profiles.get("default", {}))
    if personality is None:
        personality = profile.get("personality", "default")
    services = profile.get("services", [])
    bot_name = profile.get("telegram_bot_name")

    source = Path(base["source"])
    if not source.exists():
        raise FileNotFoundError(f"source directory not found: {source}")

    # Determine deployment path
    base_dir = fleet_base or fleet_dir()
    deploy_path = base_dir / f"microhal-{name}" / "nanoclaw"

    if deploy_path.exists():
        raise FileExistsError(f"instance already exists: {deploy_path}")

    # Copy source tree, excluding items in exclude list
    ignore_fn = _make_ignore_fn(base.get("exclude", []))
    shutil.copytree(str(source), str(deploy_path), ignore=ignore_fn)

    hlog("halctl", "info", "files_copied", {"name": name, "path": str(deploy_path)})

    # Create open directories
    _create_open_dirs(deploy_path, base.get("open", []))

    # Compose and write CLAUDE.md
    claude_md = compose_claude_md(personality, name)
    claude_path = deploy_path / "CLAUDE.md"
    claude_path.write_text(claude_md)

    # Apply lock permissions
    _apply_lock(deploy_path, base.get("lock", []))

    # Generate pm2 ecosystem config
    token_env = f"MICROHAL_{name.upper()}_BOT_TOKEN"
    eco_content = _generate_ecosystem_config(name, deploy_path, token_env)
    eco_path = base_dir / f"microhal-{name}" / "ecosystem.config.js"
    eco_path.write_text(eco_content)

    # Register in fleet manifest
    manifest = load_fleet_manifest(fleet_base=base_dir)
    entry = {
        "name": name,
        "path": str(deploy_path),
        "telegram_bot_token_env": token_env,
        "personality": personality,
        "services": services,
        "created": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "status": "active",
    }
    manifest["instances"].append(entry)
    save_fleet_manifest(manifest, fleet_base=base_dir)

    hlog("halctl", "info", "instance_created", {"name": name, "personality": personality})

    return entry


def push_instance(
    name: str,
    config_path: Path | None = None,
    fleet_base: Path | None = None,
) -> None:
    """Push locked files from prime to an existing microHAL instance."""
    cfg = load_fleet_config(config_path)
    base = cfg["base"]
    source = Path(base["source"])

    base_dir = fleet_base or fleet_dir()
    manifest = load_fleet_manifest(fleet_base=base_dir)
    instance = None
    for inst in manifest["instances"]:
        if inst["name"] == name:
            instance = inst
            break

    if instance is None:
        raise ValueError(f"instance not found: {name}")

    deploy_path = Path(instance["path"])
    if not deploy_path.exists():
        raise FileNotFoundError(f"deployment not found: {deploy_path}")

    lock_items = base.get("lock", [])

    # Temporarily unlock, copy, re-lock
    for item in lock_items:
        target = deploy_path / item
        if target.exists():
            if target.is_dir():
                for root, dirs, files in os.walk(target):
                    os.chmod(root, stat.S_IRWXU)
                    for f in files:
                        os.chmod(os.path.join(root, f), stat.S_IRUSR | stat.S_IWUSR)
                shutil.rmtree(target)
            else:
                os.chmod(target, stat.S_IRUSR | stat.S_IWUSR)
                target.unlink()

        src = source / item
        if src.is_dir():
            shutil.copytree(str(src), str(target))
        elif src.exists():
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(str(src), str(target))

    # Re-apply lock
    _apply_lock(deploy_path, lock_items)
    hlog("halctl", "info", "instance_pushed", {"name": name})


def push_all(
    config_path: Path | None = None,
    fleet_base: Path | None = None,
) -> list[str]:
    """Push locked files to all active instances. Returns list of pushed names."""
    base_dir = fleet_base or fleet_dir()
    manifest = load_fleet_manifest(fleet_base=base_dir)
    pushed = []
    for inst in manifest["instances"]:
        if inst.get("status") == "active":
            push_instance(inst["name"], config_path=config_path, fleet_base=fleet_base)
            pushed.append(inst["name"])
    return pushed


def freeze_instance(name: str, fleet_base: Path | None = None) -> None:
    """Stop process, preserve everything. Reversible."""
    base_dir = fleet_base or fleet_dir()
    manifest = load_fleet_manifest(fleet_base=base_dir)
    for inst in manifest["instances"]:
        if inst["name"] == name:
            inst["status"] = "frozen"
            save_fleet_manifest(manifest, fleet_base=base_dir)
            hlog("halctl", "info", "instance_frozen", {"name": name})
            print(f"frozen  {name}")
            print(f"\nManual step: pm2 stop microhal-{name}")
            return
    raise ValueError(f"instance not found: {name}")


def fold_instance(name: str, fleet_base: Path | None = None) -> None:
    """Stop + archive data. Not easily reversible."""
    base_dir = fleet_base or fleet_dir()
    manifest = load_fleet_manifest(fleet_base=base_dir)
    for inst in manifest["instances"]:
        if inst["name"] == name:
            inst["status"] = "folded"
            save_fleet_manifest(manifest, fleet_base=base_dir)
            hlog("halctl", "info", "instance_folded", {"name": name})
            print(f"folded  {name}")
            print(f"\nManual steps:")
            print(f"  1. pm2 stop microhal-{name}")
            print(f"  2. Revoke bot token via BotFather")
            print(f"  3. Archive data from {inst['path']}")
            return
    raise ValueError(f"instance not found: {name}")


def fry_instance(name: str, confirm: bool = False, fleet_base: Path | None = None) -> None:
    """Stop + wipe. Nuclear. Requires confirm=True."""
    if not confirm:
        raise ValueError("fry requires --confirm flag (this is destructive)")

    base_dir = fleet_base or fleet_dir()
    manifest = load_fleet_manifest(fleet_base=base_dir)
    for inst in manifest["instances"]:
        if inst["name"] == name:
            deploy_path = Path(inst["path"])
            inst["status"] = "fried"
            save_fleet_manifest(manifest, fleet_base=base_dir)

            # Unlock and delete if path exists
            if deploy_path.exists():
                instance_dir = deploy_path.parent
                # Unlock everything first
                for root, dirs, files in os.walk(instance_dir):
                    os.chmod(root, stat.S_IRWXU)
                    for f in files:
                        os.chmod(os.path.join(root, f), stat.S_IRUSR | stat.S_IWUSR)
                shutil.rmtree(instance_dir)

            hlog("halctl", "info", "instance_fried", {"name": name})
            print(f"fried  {name}  (deployment wiped)")
            print(f"\nManual step: Revoke bot token via BotFather")
            return
    raise ValueError(f"instance not found: {name}")
